# 全局代价地图
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  # 更新速率
  update_frequency: 3.0
  # 发布速率
  publish_frequency: 2.0
  static_map: true
 
  # 坐标系之间的转换可以忍受的最大延时
  transform_tolerance: 2.0
  plugins:
    - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,   type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

  inflation_layer:
    enabled:              true
    
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    # 膨胀半径
    inflation_radius:     0.50  # max. distance from an obstacle at which costs are incurred for planning paths.





