local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 2.0
  # 局部代价地图需要在机器人移动时检测周围是否有新增的障碍物
  static_map: false
  # 机器人移动时保证机器人在滚动窗口中心
  rolling_window: true
  width: 5.0  #滚动窗口宽度
  height: 5.0 #滚动窗口高度
  resolution: 0.05
  transform_tolerance: 2.0
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.35  # max. distance from an obstacle at which costs are incurred for planning paths.

